//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YurtDb.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class YurtDBEntities : DbContext
    {
        public YurtDBEntities()
            : base("name=YurtDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<basvurular> basvurular { get; set; }
        public virtual DbSet<Donem> Donem { get; set; }
        public virtual DbSet<donemTipi> donemTipi { get; set; }
        public virtual DbSet<evrakBilgileri> evrakBilgileri { get; set; }
        public virtual DbSet<evrakTipi> evrakTipi { get; set; }
        public virtual DbSet<indirimler> indirimler { get; set; }
        public virtual DbSet<Kayıt> Kayıt { get; set; }
        public virtual DbSet<odaFiyatlari> odaFiyatlari { get; set; }
        public virtual DbSet<odaTipi> odaTipi { get; set; }
        public virtual DbSet<odaTipiKontenjan> odaTipiKontenjan { get; set; }
        public virtual DbSet<ogrenci> ogrenci { get; set; }
        public virtual DbSet<ogrenciApi> ogrenciApi { get; set; }
    
        public virtual int basvur(string ogrenciNo, Nullable<int> odaTipiID, string cinsiyet, ObjectParameter islemDurumu)
        {
            var ogrenciNoParameter = ogrenciNo != null ?
                new ObjectParameter("ogrenciNo", ogrenciNo) :
                new ObjectParameter("ogrenciNo", typeof(string));
    
            var odaTipiIDParameter = odaTipiID.HasValue ?
                new ObjectParameter("odaTipiID", odaTipiID) :
                new ObjectParameter("odaTipiID", typeof(int));
    
            var cinsiyetParameter = cinsiyet != null ?
                new ObjectParameter("cinsiyet", cinsiyet) :
                new ObjectParameter("cinsiyet", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("basvur", ogrenciNoParameter, odaTipiIDParameter, cinsiyetParameter, islemDurumu);
        }
    
        public virtual ObjectResult<kontenjanSayisi_Result> kontenjanSayisi(string cinsiyet)
        {
            var cinsiyetParameter = cinsiyet != null ?
                new ObjectParameter("cinsiyet", cinsiyet) :
                new ObjectParameter("cinsiyet", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<kontenjanSayisi_Result>("kontenjanSayisi", cinsiyetParameter);
        }
    }
}
