//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YurtDb.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kayıt
    {
        public int id { get; set; }
        public Nullable<int> ogrenciNo { get; set; }
        public Nullable<int> odaBilgileri { get; set; }
        public Nullable<int> donemTipiID { get; set; }
    
        public virtual donemTipi donemTipi { get; set; }
        public virtual odaFiyatlari odaFiyatlari { get; set; }
    }
}
