//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YurtDb.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class odaTipiKontenjan
    {
        public int odaTipiKontenjanID { get; set; }
        public Nullable<int> erkekKontenjan { get; set; }
        public Nullable<int> kizKontenjan { get; set; }
        public Nullable<int> toplam { get; set; }
        public Nullable<int> odaTipiID { get; set; }
        public Nullable<int> donemTipiID { get; set; }
    
        public virtual donemTipi donemTipi { get; set; }
        public virtual odaTipi odaTipi { get; set; }
    }
}
