//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YurtDb.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class odaTipi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public odaTipi()
        {
            this.odaFiyatlari = new HashSet<odaFiyatlari>();
        }
    
        public int odaTipiID { get; set; }
        public string adi { get; set; }
        public Nullable<int> odaKontenjan { get; set; }
        public Nullable<int> odaTipiKontenjanID { get; set; }
        public Nullable<int> donemTipiID { get; set; }
    
        public virtual donemTipi donemTipi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<odaFiyatlari> odaFiyatlari { get; set; }
        public virtual odaTipiKontenjan odaTipiKontenjan { get; set; }
    }
}
