//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YurtDb.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ogrenciApi
    {
        public string ogrenciNo { get; set; }
        public Nullable<long> tcNo { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public string egitimDurumu { get; set; }
        public string fakulteNo { get; set; }
        public string bolumNo { get; set; }
        public string cinsiyet { get; set; }
    }
}
