//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YurtDb.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YurtDatabaseEntities : DbContext
    {
        public YurtDatabaseEntities()
            : base("name=YurtDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Donem> Donems { get; set; }
        public virtual DbSet<donemTipi> donemTipis { get; set; }
        public virtual DbSet<evrakBilgileri> evrakBilgileris { get; set; }
        public virtual DbSet<evrakTipi> evrakTipis { get; set; }
        public virtual DbSet<indirimler> indirimlers { get; set; }
        public virtual DbSet<Kayıt> Kayıt { get; set; }
        public virtual DbSet<odaFiyatlari> odaFiyatlaris { get; set; }
        public virtual DbSet<odaTipi> odaTipis { get; set; }
        public virtual DbSet<odaTipiKontenjan> odaTipiKontenjans { get; set; }
        public virtual DbSet<ogrenci> ogrencis { get; set; }
    }
}
