//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YurtDb.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YurtDBEntities : DbContext
    {
        public YurtDBEntities()
            : base("name=YurtDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Donem> Donem { get; set; }
        public virtual DbSet<donemTipi> donemTipi { get; set; }
        public virtual DbSet<evrakBilgileri> evrakBilgileri { get; set; }
        public virtual DbSet<evrakTipi> evrakTipi { get; set; }
        public virtual DbSet<indirimler> indirimler { get; set; }
        public virtual DbSet<Kayıt> Kayıt { get; set; }
        public virtual DbSet<odaFiyatlari> odaFiyatlari { get; set; }
        public virtual DbSet<odaTipi> odaTipi { get; set; }
        public virtual DbSet<odaTipiKontenjan> odaTipiKontenjan { get; set; }
        public virtual DbSet<ogrenci> ogrenci { get; set; }
        public virtual DbSet<ogrenciApi> ogrenciApi { get; set; }
    }
}
